---
 apiVersion: extensions/v1beta1
 kind: Deployment
 metadata:
   name: calculator
 spec:
   replicas: 2
   template:
     metadata:
       labels:
         app: calculator
     spec:
       containers:
         - name: calculator
           image: allantargino/calculator:latest
           ports:
             - containerPort: 5000
---
kind: Service
apiVersion: v1
metadata:
  name: calculator
spec:
  selector:
    app: calculator
  ports:
  - port: 5000
    targetPort: 5000
    name: http
---
 apiVersion: extensions/v1beta1
 kind: Deployment
 metadata:
   name: frontend
 spec:
   replicas: 2
   template:
     metadata:
       labels:
         app: frontend
     spec:
       containers:
         - name: frontend
           image: allantargino/frontend-calculator:latest
           ports:
             - containerPort: 5001
---
kind: Service
apiVersion: v1
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
  - port: 5001
    targetPort: 5001
    name: http
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gatewaycalculator
  annotations:
    kubernetes.io/ingress.class: "istio"
spec:
  rules:
  - http:
      paths:
      - path: /.*
        backend:
          serviceName: frontend
          servicePort: 5001
---